export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REDUCE_CART_QUANTITY: 'REDUCE_CART_QUANTITY',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM'
};